spring:
  application: 
    name: config-server
  cloud: 
   config:  
    server: 
     git: 
      uri: https://github.com/WarnerTao/spring-cloud-config.git
      search-paths: spring-cloud-config
      

  
server:
 port: 8888
 
 
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#spring.cloud.config.server.git.username=your username
#spring.cloud.config.server.git.password=your password